[package]
name = "alloy-ephemeral-lens"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = { version = "0.13.0", features = ["full"] }
hex = "0.4.3"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"] }
tokio-test = "0.4.4"
